### ISSUE TITLE
ERRORs in home-assistant.log

### ISSUE THREAD

**Issue by andreasfromch** [korylprince/hassio-apcupsd#1]
Hi, 

I’ve installed the APC UPS Daemon form here.

That’s my config:

{
  "name": "UPS1",
  "cable": "usb",
  "type": "usb",
  "device": "",
  "extra": []
}

Now I get the following error in my log file. Are there any advices for that?

17-12-16 08:12:19 ERROR (MainThread) [homeassistant.setup] Error during setup of component apcupsd
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 193, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/apcupsd.py", line 44, in setup
    conf = config[DOMAIN]
KeyError: 'apcupsd'
2017-12-16 08:12:19 ERROR (MainThread) [homeassistant.setup] Unable to setup dependencies of sensor.apcupsd. Setup failed for dependencies: apcupsd
2017-12-16 08:12:19 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.apcupsd: Could not setup all dependencies.

Regards,

Andreas

**Comment by korylprince** [comment]
What's your config look like? It should look something like:

```
apcupsd:
  host: a722577e-apcupsd
```

**Comment by andreasfromch** [comment]
Where can I find "text like Made available via repository ..."?
Please see the attached Screenshot.

![image](https://user-images.githubusercontent.com/30843010/34441636-53db7144-ecbd-11e7-832f-e1c8b99bb560.png)

**Comment by korylprince** [comment]
@andreasfromch 

I looked at the hassio code and the ID is generated from the repository name, so it should be the same for everyone.

But to answer your question, go to the Hassio panel, click the store icon in the top right then click the add-on in the list:

![image](https://user-images.githubusercontent.com/559762/34085849-a4120fd0-e35b-11e7-9eca-a60c29343861.png)

**Comment by andreasfromch** [comment]
@korylprince

Thanks for the great support!
The problem was the missing
```
apcupsd:
  host: a722577e-apcupsd
```
in configuration.yaml and more than one restart.
Now everything is fine and the component works very well!

**Comment by korylprince** [comment]
@andreasfromch I'm glad someone is using it! I've added more information about the home assistant configuration on the README about this issue. Thanks for submitting this.
