### ISSUE TITLE
sensors couldn't be setup

### ISSUE THREAD

**Issue by Jens-Wymeersch** [korylprince/hassio-apcupsd#27]
Hi,

I've installed the APCUPSD correctly on a windows machine. 
My model is a Back-UPS ES 850G2. The IP address indicated by the daemon is 127.0.0.1 but is different from the machine on which it is running. My Home Assistant is installed as VirtualBox image. So both programs are running on different systems. 

The error logs can be found below. 

Regards,
Jens

`Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/apcupsd/__init__.py", line 49, in setup
apcups_data.update(no_throttle=True)
File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
result = method(*args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/apcupsd/__init__.py", line 85, in update
self._status = self._get_status()
File "/usr/src/homeassistant/homeassistant/components/apcupsd/__init__.py", line 80, in _get_status
return self._parse(self._get(host=self._host, port=self._port))
File "/usr/local/lib/python3.8/site-packages/apcaccess/status.py", line 37, in get
sock.connect((host, port))
socket.timeout: timed out
2020-11-23 12:27:14 ERROR (MainThread) [homeassistant.setup] Setup failed for apcupsd: Integration failed to initialize.
2020-11-23 12:27:14 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform apcupsd.binary_sensor: Unable to set up component.`

**Comment by korylprince** [comment]
I have made the decision to archive this repository. Please see the README for more information.
