### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by GeoHolz** [korylprince/hassio-apcupsd#8]
In the dashboard :
The following components and platforms could not be set up:

    apcupsd
    sensor.apcupsd

In log frontend:
Please check your config.

Unable to prepare setup for platform sensor.apcupsd: Could not set up all dependencies.
11:03 setup.py (ERROR)
Unable to set up dependencies of sensor.apcupsd. Setup failed for dependencies: apcupsd
11:03 setup.py (ERROR)
Setup failed for apcupsd: Component failed to initialize.
11:03 setup.py (ERROR)
Failure while testing APCUPSd status retrieval.
11:03 components/apcupsd.py (ERROR)

In home-assistant.log : 
2019-01-18 10:03:08 ERROR (SyncWorker_4) [homeassistant.components.apcupsd] Failure while testing APCUPSd status retrieval.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/apcupsd.py", line 53, in setup
    DATA.update(no_throttle=True)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 315, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/apcupsd.py", line 89, in update
    self._status = self._get_status()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/apcupsd.py", line 84, in _get_status
    return self._parse(self._get(host=self._host, port=self._port))
  File "/usr/local/lib/python3.6/site-packages/apcaccess/status.py", line 37, in get
    sock.connect((host, port))
socket.gaierror: [Errno -2] Name does not resolve
2019-01-18 10:03:08 ERROR (MainThread) [homeassistant.setup] Setup failed for apcupsd: Component failed to initialize.
2019-01-18 10:03:08 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of sensor.apcupsd. Setup failed for dependencies: apcupsd
2019-01-18 10:03:08 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform sensor.apcupsd: Could not set up all dependencies.

**Comment by GeoHolz** [comment]
https://developers.home-assistant.io/docs/en/hassio_addon_communication.html
You can use this name also as DNS name but you need replace the _ with - to have a valid hostname.

So, replace a722577e-apcupsd_net for a722577e-apcupsd-net

**Comment by GeoHolz** [comment]
Now i have 
2019-01-18 10:25:14 WARNING (SyncWorker_0) [homeassistant.components.sensor.apcupsd] Sensor type: bcharge does not appear in the APCUPSd status output
2019-01-18 10:25:14 WARNING (SyncWorker_0) [homeassistant.components.sensor.apcupsd] Sensor type: linev does not appear in the APCUPSd status output

**Comment by korylprince** [comment]
Thanks, I updated the README to reflect the correct hostname: 0f89282
